# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: meta
    hooks:
    - id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: sort
        name: isort
        entry: poetry
        args:
            - run
            - isort
            - src
            - tests
        language: system
        types: [ python ]
        require_serial: true
    -   id: black
        name: black
        entry: poetry
        args:
            - run
            - black
            - -l 120
        language: system
        types: [ python ]
        require_serial: true
    -   id: flake8
        name: flake8
        entry: poetry
        args:
            - run
            - flake8
            - --max-cognitive-complexity=15
        language: system
        types: [python]
        require_serial: true
        files: '(src|test)/.*\.py'
    -   id: mypy
        name: mypy
        entry: poetry
        args:
            - run
            - mypy
        files: 'src/.*\.py'
        language: system
        types: [python]
        require_serial: true
